<?php
session_start();
//Checking login or not
if (!isset($_SESSION['username'])) {
	header("location: login.php");
}
include 'dbcon.php';
$API = "rzp_test_bCJTYBVFqyOlsx";
$name = $_SESSION['username'];
$email = $_SESSION['email'];
$user_id = $_SESSION['id'];
$user_query = "select * from user where email = '$email'";
$user_query_run = mysqli_query($conn, $user_query);
$user_fetch = mysqli_fetch_assoc($user_query_run);

//Generating  transaction id
$tid = "LU-" . bin2hex(random_bytes(16));

//Creating Countdown
$today = date("d-m-Y");
$plan_expire = $user_fetch['plan_expire'];
$plan_expiration = date("d-m-Y", strtotime($plan_expire));
$dateDiff = strtotime($plan_expiration) - strtotime($today);
$Daysleft = floor($dateDiff / (60 * 60 * 24));
?>
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Premium | ListenUp</title>

	<!-- Meta -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="ListenUp audiobook platfrom">
	<meta name="author" content="ListenUp">
	<link rel="shortcut icon" href="favicon.ico">

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700&display=swap" rel="stylesheet">

	<!-- FontAwesome JS-->
	<script defer src="assets/fontawesome/js/all.min.js"></script>

	<!-- Theme CSS -->
	<link id="theme-style" rel="stylesheet" href="assets/css/theme.css">

	<link rel="stylesheet" type="text/css" href="css/down-nav.css">


	<style type="text/css">
		.msger-inputarea {
			display: flex;
			padding: 10px;
			border-top: var(--border);
			background: #eee;
		}

		.msger-inputarea * {
			padding: 10px;
			border: none;
			border-radius: 3px;
			font-size: 1em;
		}

		.msger-input {
			flex: 1;
			background: #ddd;
		}

		.msger-send-btn {
			margin-left: 10px;
			background: rgb(0, 196, 65);
			color: #fff;
			font-weight: bold;
			cursor: pointer;
			transition: background 0.23s;
		}

		.msger-send-btn:hover {
			background: rgb(0, 180, 50);
		}
	</style>

</head>

<body>
	<?php include 'header.php'; ?>



	<div class="page-content">
		<div class="container">
			<div class="docs-overview py-5">
				<div class="row justify-content-center">


					<div class="col-12 col-lg-9 py-3">
						<div class="card shadow-sm">
							<div class="card-body">
								<center>
									<h4 class="card-title mb-3">
										<span class="card-title-text">My Plan</span>
									</h4>
									<h1 class="card-title mb-3">
										<span class="card-title-text">
											<?php
											if ($user_fetch['plan'] == 1) {
												echo "Monthly Plan";
											} elseif ($user_fetch['plan'] == 2) {
												echo "Yearly Plan";
											} else {
												echo "Free Plan";
											}
											?>
										</span>
									</h1>
									<h4 class="card-title-text">
										<?php
										if (($user_fetch['plan'] == 1) or ($user_fetch['plan'] == 2)) {
											echo "Days left: " . $Daysleft;
										}
										?>
									</h4>
								</center>
							</div><!--//card-body-->
						</div><!--//card-->
					</div><!--//col-->




					<!--Monthly Plan-->
					<div class="col-12 col-lg-4 py-3">
						<div class="card shadow-sm">
							<div class="card-body">
								<center>
									<h4 class="card-title mb-3">
										<span class="card-title-text">Monthly</span>
									</h4>
									<h1 class="card-title mb-3">
										<span class="card-title-text">₹199</span>
									</h1>
									<h5 class="card-title mb-3">
										<span class="card-title-text">Benifits</span>
										<hr>
									</h5>
								</center>
								<span class="card-title-text"><b>Days:</b> 30</span><br>
								<span class="card-title-text"><b>Ads Free:</b> YES</span><br>
								<span class="card-title-text"><b>Premium Books:</b> YES</span>
								<br><br>
								<center>
									<?php
									if ($user_fetch['plan'] == 0) {
										?>
										<form
											action="http://localhost/audiobook2/success.php?tid=<?php echo $tid ?>&user_id=<?php echo $user_id ?>&plan=1"
											method="POST">
											<script src="https://checkout.razorpay.com/v1/checkout.js"
												data-key="<?php echo $API; ?>" /* Enter the Test API Key ID generated from
												Dashboard → Settings → API Keys*/ 
												data-amount="<?php echo 199 * 100; ?>" //
												Amount is in currency subunits. Hence, 29935 refers to 29935 paise or
												₹299.35. data-currency="INR" // You can accept international payments by
												changing the currency code. Contact our Support Team to enable International
												for your account data-id="<?php echo $tid; ?>" // Replace with the order_id
												generated by you in the backend. data-buttontext="Upgrade Plan"
												data-description="Monthly Play" data-image="assets/images/logo.png"
												data-name="<?php echo "ListenUp"; //$name; ?>"
												data-prefill.name="<?php echo $name; ?>"
												data-prefill.email="<?php echo $email; ?>"
												data-theme.color="#28b76b"></script>
											<input type="hidden" custom="Hidden Element" class="btn btn-primary" name="hidden" />
										</form>
										<?php
									}
									?>
								</center>

							</div><!--//card-body-->
						</div><!--//card-->
					</div><!--//col-->



					<!--Yearly Plan-->
					<div class="col-12 col-lg-4 py-3">
						<div class="card shadow-sm">
							<div class="card-body">
								<center>
									<h4 class="card-title mb-3">
										<span class="card-title-text">Yearly</span>
									</h4>
									<h1 class="card-title mb-3">
										<span class="card-title-text">₹365</span>
									</h1>
									<h5 class="card-title mb-3">
										<span class="card-title-text">Benifits</span>
										<hr>
									</h5>
								</center>
								<span class="card-title-text"><b>Days:</b> 365</span><br>
								<span class="card-title-text"><b>Ads Free:</b> YES</span><br>
								<span class="card-title-text"><b>Premium Books:</b> YES</span>
								<br><br>
								<center>
									<?php
									if ($user_fetch['plan'] == 0 or $user_fetch['plan'] == 1) {
										?>
										<form
											action="http://localhost/audiobook2/success.php?tid=<?php echo $tid ?>&user_id=<?php echo $user_id ?>&plan=2"
											method="POST">
											<script src="https://checkout.razorpay.com/v1/checkout.js"
												data-key="<?php echo $API; ?>" /* Enter the Test API Key ID generated from
												Dashboard → Settings → API Keys*/ data-amount="<?php echo 365 * 100; ?>" //
												Amount is in currency subunits. Hence, 29935 refers to 29935 paise or
												₹299.35. data-currency="INR" // You can accept international payments by
												changing the currency code. Contact our Support Team to enable International
												for your account data-id="<?php echo $tid; ?>" // Replace with the order_id
												generated by you in the backend. data-buttontext="Upgrade Plan"
												data-description="Yearly Play" data-image="assets/images/logo.png"
												data-name="<?php echo "ListenUp"; //$name; ?>"
												data-prefill.name="<?php echo $name; ?>"
												data-prefill.email="<?php echo $email; ?>"
												data-theme.color="#28b76b"></script>
											<input type="hidden" custom="Hidden Element" name="hidden" />
										</form>
										<?php
									}
									?>
								</center>

							</div><!--//card-body-->
						</div><!--//card-->
					</div><!--//col-->






				</div><!--//row-->
			</div><!--//container-->
		</div><!--//container-->
	</div><!--//page-content-->

	<!--<section class="cta-section text-center py-5 theme-bg-dark position-relative">
		<div class="theme-bg-shapes-right"></div>
		<div class="theme-bg-shapes-left"></div>
		<div class="container">
			<h3 class="mb-2 text-white mb-3">Launch Your Software Project Like A Pro</h3>
			<div class="section-intro text-white mb-3 single-col-max mx-auto">Want to launch your software project and start getting traction from your target users? Check out our premium <a class="text-white" href="https://themes.3rdwavemedia.com/bootstrap-templates/startup/coderpro-bootstrap-5-startup-template-for-software-projects/">Bootstrap 5 startup template CoderPro</a>! It has everything you need to promote your product.</div>
			<div class="pt-3 text-center">
				<a class="btn btn-light" href="https://themes.3rdwavemedia.com/bootstrap-templates/startup/coderpro-bootstrap-5-startup-template-for-software-projects/">Get CoderPro<i class="fas fa-arrow-alt-circle-right ml-2"></i></a>
			</div>
		</div>
	</section>//cta-section-->




	<footer class="footer">

		<div class="footer-bottom text-center py-5">




		</div>

	</footer>

	<!-- Javascript -->
	<script src="assets/plugins/popper.min.js"></script>
	<script src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>

	<!-- Page Specific JS -->
	<script src="assets/plugins/smoothscroll.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/highlight.min.js"></script>
	<script src="assets/js/highlight-custom.js"></script>
	<script src="assets/plugins/simplelightbox/simple-lightbox.min.js"></script>
	<script src="assets/plugins/gumshoe/gumshoe.polyfills.min.js"></script>
	<script src="assets/js/docs.js"></script>


	<!--Down Nav-->
	<nav class="nav">
		<a href="dashboard.php" class="nav-link">
			<i class="fa fa-home"></i>
			<span class="nav-text">Dashboard</span>
		</a>

		<a href="premium.php" class="nav-link active">
			<i class="fa fa-gem"></i>
			<span class="nav-text">Premium</span>
		</a>

		<a href="categories.php" class="nav-link">
			<i class="fa fa-align-justify"></i>
			<span class="nav-text">Category</span>
		</a>

		<a href="library.php" class="nav-link">
			<i class="far fa-list-alt"></i>
			<span class="nav-text">Library</span>
		</a>
	</nav>
</body>

</html>