<?php
    $advertiser_id = $_GET['advertiser_id'];
    $name = $_GET['name'];
    $API = $_GET['api'];
    $balance = $_GET['balance'];
    $tid = bin2hex(random_bytes(16));

    


?>
<center>
Click here to continue
<form action="http://localhost/audiobook2/advertiser/success.php?tid=<?php echo $tid ?>&advertiser_id=<?php echo $advertiser_id ?>&balance=<?php echo $balance ?>" method="POST">
											<script
										    src="https://checkout.razorpay.com/v1/checkout.js"
										    data-key="<?php echo $API; ?>" /* Enter the Test API Key ID generated from Dashboard → Settings → API Keys*/
										    data-amount="<?php echo $balance*100 ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
										    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
										    data-id="<?php echo $tid; ?>"// Replace with the order_id generated by you in the backend.
										    data-buttontext="Add Balance"
										    data-description="Add balance to your advertiser account"
										    data-image="../assets/images/logo.png"
										    data-name="<?php echo "ListenUp";//$name; ?>"
										    data-prefill.name="<?php echo $name; ?>"
										    data-prefill.email="<?php echo $email; ?>"
										    data-theme.color="#28b76b"
											></script>
											<input type="hidden"  custom="Hidden Element" name="hidden"/>
										</form>
</center>